"""Add duration_seconds to game_sessions

Revision ID: d58d04a64c1e
Revises: 3f2b17c9b3ed
Create Date: 2026-08-15 18:47:22.887914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58d04a64c1e'
down_revision: Union[str, Sequence[str], None] = '3f2b17c9b3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('duration_seconds', sa.Integer(), server_default='60', nullable=False))
    op.drop_index(op.f('ix_game_sessions_leaderboard_global'), table_name='game_sessions')
    op.create_index('ix_game_sessions_leaderboard_global', 'game_sessions', ['status', 'duration_seconds', sa.literal_column('score DESC')], unique=False)
    op.drop_index(op.f('ix_game_sessions_leaderboard_timeframe'), table_name='game_sessions')
    op.create_index('ix_game_sessions_leaderboard_timeframe', 'game_sessions', ['status', 'duration_seconds', 'started_at', sa.literal_column('score DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_sessions_leaderboard_timeframe', table_name='game_sessions')
    op.create_index(op.f('ix_game_sessions_leaderboard_timeframe'), 'game_sessions', ['status', 'started_at', sa.literal_column('score DESC')], unique=False)
    op.drop_index('ix_game_sessions_leaderboard_global', table_name='game_sessions')
    op.create_index(op.f('ix_game_sessions_leaderboard_global'), 'game_sessions', ['status', sa.literal_column('score DESC')], unique=False)
    op.drop_column('game_sessions', 'duration_seconds')
    # ### end Alembic commands ###
